POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username":"pina771",
  "password":"pina771"
}

###

GET http://localhost:3000/posts

###
PATCH http://localhost:3000/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpbmE3NzEiLCJzdWIiOjQsImlhdCI6MTY1NTkyMjAwMSwiZXhwIjoxNjU1OTQzNjAxfQ.ymkKCMk0oQ4hEgZOw0NZKc21_6kTQ2BUkM4QArmQGAQ
Content-Type: application/json

{
  "description": "GOodbye, trust."
}

